---
creation_rules:
  # Encrypt all files ending with -secret.yaml or secret.yaml in the clusters directory
  - path_regex: clusters/.*/.*secret\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1t7mjzrw5a3ch5vxzdk7sxj3q9qpj36qmjnskq4h408ne658r3quq75y8tu
  
  # Encrypt all files in a secrets/ directory
  - path_regex: clusters/.*/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1t7mjzrw5a3ch5vxzdk7sxj3q9qpj36qmjnskq4h408ne658r3quq75y8tu
