---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 5m
  chart:
    spec:
      chart: actions-runner-controller
      version: "0.23.x"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  install:
    createNamespace: false
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # GitHub authentication secret configuration
    authSecret:
      enabled: true
      create: false
      name: github-pat
    
    # Controller configuration
    controllerManager:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 256Mi
      # Allow scheduling on control-plane nodes
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    
    # Webhook configuration
    webhookServer:
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi

    # Metrics server disabled to save resources
    metricsServer:
      enabled: false

