apiVersion: v1
kind: Secret
metadata:
    name: loki-push-basic-auth
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:N/919zLG2kN2C6QQ6vP/SbhdqoPmh2aRZXK9QK+vH1neQJyNPcSgMPl1E9ABvliDvWqr3TvE6fIgOVrMnyJlaAdi,iv:zUy+UZsL4Fq6WaBaENRkdWbs07G9C8N1OSlL4D2VEEc=,tag:7akrqNg7DoWIgFmbhP0fNQ==,type:comment]
    #ENC[AES256_GCM,data:5rotGDsJjs+KJwK3lfnhBG1gm8Q531GKokOct2NPzPbGSVSZrK+hRwR92i9xEPJVtm/NQ7T6hb8XaYImcOYbMG59l9Z6LWaKcoZiC9N+2w==,iv:47hFZ6Xbeff3qQh0b1lIAS/mSf1phl+UBul8fYInzsA=,tag:E8gZvVm1KbBjrD8Y2muppg==,type:comment]
    .htpasswd: ENC[AES256_GCM,data:RkkjnNR3/N93AmXYYMMS94mKwR8Jecx2Vx2F7+WQSg6eCb5jcju6A/fV9bkPqg==,iv:VyjMcMEceaLxIhkSRYcAJIcOFWmNfYLxK1f4veBx3rY=,tag:Ph52iAsT5CoNvExDE3CZ0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7mjzrw5a3ch5vxzdk7sxj3q9qpj36qmjnskq4h408ne658r3quq75y8tu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVk1BWUltaVZCckpwbG1C
            V0hZSjVESldLODI0d1pYRFpYVU9QUms5QUM0CkxBM2lCNWNKKy8zVWJTaUpUYU51
            b01KTDRnQ0xIdjJYby9EK2x5SDFpSkkKLS0tIGpMd0ExcE92b1owSWptd3ArYTZL
            cnhOZW9VY2JCTENienFCaGVpdW1zZXMKFUxbQlTYp9GQ1VgrwNnDtO8UNYFoy1Rb
            mRs3TKsShn5+jIYwIRc6tgGe0Cb1m/IVwTifYELuqVHMARwUzPjouw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T16:38:44Z"
    mac: ENC[AES256_GCM,data:uUElFhZ8O6e/kuTsE1ZVTvp/LdPesi+agWEMIZsmdLKQebKGVkcv0MkSP31oT0cwiRBqFiL/swJ2dCk1g1loYSQMiZ3UeElRBGC6kfH+2GGI++fxX8wnStW69qbvqEuC3FK5aMAfUmYazLxB0yjQ0YMW8tVyI3qv6YNGLX6Or4A=,iv:NNR8gNnDKbrZD4H55TTSp935PmnGZKizOBtF9U5wKA8=,tag:QfECxvOelwMKTRDtD1LXgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
