---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # Single binary mode for resource efficiency on Raspberry Pi
    deploymentMode: SingleBinary
    
    loki:
      auth_enabled: false
      
      commonConfig:
        replication_factor: 1
      
      # Storage configuration
      storage:
        type: filesystem
      
      # Schema configuration for structured logs
      schemaConfig:
        configs:
          - from: 2024-01-01
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      
      # Limits
      limits_config:
        retention_period: 168h  # 7 days
        ingestion_rate_mb: 10
        ingestion_burst_size_mb: 20
        max_query_series: 1000
        max_query_parallelism: 16
        
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
      persistence:
        enabled: true
        size: 10Gi
        storageClass: longhorn
    
    # Disable components not needed in single binary mode
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    
    # Enable metrics for Prometheus
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
    
    # Service configuration
    gateway:
      enabled: false
    
    # Disable test pods
    test:
      enabled: false
