---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # Run as DaemonSet on all nodes
    daemonset:
      enabled: true
    
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push
      
      # Structured logging configuration
      snippets:
        # Parse JSON logs automatically
        pipelineStages:
          - cri: {}
          # Extract JSON fields if present
          - json:
              expressions:
                level: level
                message: message
                timestamp: timestamp
          # Add labels for structured querying
          - labels:
              level:
          # Parse common log formats
          - match:
              selector: '{app="prometheus"}'
              stages:
                - regex:
                    expression: '^(?P<timestamp>\\S+)\\s+(?P<level>\\S+)\\s+(?P<message>.*)'
                - labels:
                    level:
          # Extract Kubernetes metadata
          - labeldrop:
              - filename
    
    # Resource limits for Raspberry Pi
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
    
    # Mount host paths to collect logs
    extraVolumes:
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: pods
        hostPath:
          path: /var/log/pods
    
    extraVolumeMounts:
      - name: containers
        mountPath: /var/lib/docker/containers
        readOnly: true
      - name: pods
        mountPath: /var/log/pods
        readOnly: true
    
    # Tolerate all taints to run on all nodes
    tolerations:
      - effect: NoSchedule
        operator: Exists
