---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: robopd2-api
  namespace: robopd2
spec:
  imageRepositoryRef:
    name: robopd2-api
  filterTags:
    pattern: '^main-(\d{14})$'
    extract: '$1'
  policy:
    alphabetical:
      order: asc
