---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/home/infra/configs/envoy-gateway
  prune: true
  wait: false
  timeout: 5m
  dependsOn:
    - name: cert-manager-controller
