apiVersion: v1
kind: Secret
metadata:
    name: eufy-credentials
    namespace: home-assistant
type: Opaque
stringData:
    USERNAME: ENC[AES256_GCM,data:SsZQL0UJAE+FwaT+wWK6mNbYuB0fIP/mtg==,iv:KvSXgVV05k/F3MUbgGEFxgUT4tU9CZX2s79uFbHdZeU=,tag:If7mhN9xhnSG/ahIVyLktQ==,type:str]
    PASSWORD: ENC[AES256_GCM,data:5ahCov49aqjW+wR8IQ==,iv:j6vRLl0kujtNbnO4698IEdMC0gk+Xj945QPDbue+H1s=,tag:XhQcl1boEdsU2k0CWB7rBw==,type:str]
    COUNTRY: ENC[AES256_GCM,data:HcU=,iv:xD7ImZ7D6iqokMKw+BwTC0ZXWbqJTUJJUyXzh/jDnz8=,tag:mJ+IT3GfLlg5wbzD8JgyGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7mjzrw5a3ch5vxzdk7sxj3q9qpj36qmjnskq4h408ne658r3quq75y8tu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRHM5STZNUEVRWmVIb1NG
            QXFSNlc1NHBVbXpGSHZHak1ncXpRR1BoUXpZClRWSEFCOGY4VUZSTFM2Vi9xc3Jj
            RWl4UVJzVE0yK2hxYmNYOEtlbzlnQzQKLS0tIFNiSGVoRDI0dUdaaU5tTUJQQ0li
            TWU1MnhaU3FBa2FLMjFxRzh2Rk1rVWcKsEj0bodNefS3jEA4VpkA7lcZNGdOl297
            OcmTGvK/NcMDKxOdGgK8UkyN6Dy+dyxyF0+vx8M8PSus8Li7HZspZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T23:52:03Z"
    mac: ENC[AES256_GCM,data:Pis+9d+f73x8Hila+agnrpeHiXpSbgr2C/darABdcDv3CARcyPLDXyTshjSR+Wzf4O+TdVhevYjOmgIVG8Dq5kEZHgR/gCJjLbqJINmslvE1vqyfWhdJeaibkPhkQDkvTmoCwNYpCEDOWdIA5s1Dc0t2WlPfKK7k93/DaNgugn8=,iv:171IAPDMHD17wfu43Ef1B9JaDriXPZFv/XUbd1LSYak=,tag:9ClHC+j50UCIIraM3h+/nA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
